# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.treeView = QtWidgets.QTreeView(parent=Dialog)
        self.treeView.setGeometry(QtCore.QRect(70, 40, 256, 192))
        self.treeView.setObjectName("treeView")
        self.verticalSlider = QtWidgets.QSlider(parent=Dialog)
        self.verticalSlider.setGeometry(QtCore.QRect(130, 50, 16, 160))
        self.verticalSlider.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.keySequenceEdit = QtWidgets.QKeySequenceEdit(parent=Dialog)
        self.keySequenceEdit.setGeometry(QtCore.QRect(180, 50, 113, 25))
        self.keySequenceEdit.setObjectName("keySequenceEdit")
        self.keySequenceEdit_2 = QtWidgets.QKeySequenceEdit(parent=Dialog)
        self.keySequenceEdit_2.setGeometry(QtCore.QRect(180, 90, 113, 25))
        self.keySequenceEdit_2.setObjectName("keySequenceEdit_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
