[tool.poetry]
name = "tes-myload"
version = "0.1.0"
description = "Myload Teamproject"
authors = ["MyLoad-Team"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^5.1.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
